### ISSUE TITLE
EXC_BAD_ACCESS in ZXCapture replaceInput method

### ISSUE THREAD

**Issue by maxkorytko** [TheLevelUp/ZXingObjC#294]
Hi,

I'm testing my app in iOS 10 and Xcode 8 beta 3. I've come across an app crash in ZCCapture class. I'm using CocoaPods to bring ZXingObjC into my project: pod 'ZXingObjC', '3.1.0'

The crash started to happen in iOS 10.

Attached is the screenshot:

![image](https://cloud.githubusercontent.com/assets/5502840/17462047/fea5e348-5c6d-11e6-931c-bf388a6de6d8.png)

Please help.

**Comment by rayapudicb** [comment]
![screen shot 2016-09-12 at 5 02 42 pm](https://cloud.githubusercontent.com/assets/3790822/18434433/b7f70846-790a-11e6-819a-e4726546cfa5.png)

I have got the same issue on XCode Version 8.0 beta 6
Please help me with the issue.

**Comment by maxkorytko** [comment]
Hi @rayapudicb ,

Are you getting this error when you run your app in a simulator? Basically, I discovered that when I run my app in the simulator, I get this error. When I run the app on a device, I don't.
Based on my investigation, this error occurs in the simulator, because it does not have a camera. I fixed the issue by checking if a camera is available prior to attempting to access it.

Hope this helps.

**Comment by rayapudicb** [comment]
Hi @maxkorytko Max,
1)First i got the Crash on the device which i updated to iOS 10,after that i thought of debugging the issue i run the app on the simulator which gave a bad access.
2)i also got a issue while accessing the camera album on the simulator for that i added the property in Plist which worked fine,First was not fixed,can u please let me know what is the property u added for checking the camera is available r not.?
Thanks in advance,
Chinni.

**Comment by maxkorytko** [comment]
Hi @rayapudicb ,

Here is the code:

`- (void)startBarCodeCapture {
    if ([[AVCaptureDevice devicesWithMediaType:AVMediaTypeVideo] count] == 0) {
        [self notifyCameraNotAvailable];
        return;
    }
    
    switch ([AVCaptureDevice authorizationStatusForMediaType:AVMediaTypeVideo]) {
        case AVAuthorizationStatusDenied:
            [self notifyCameraAuthorizationDenied];
            break;
        case AVAuthorizationStatusRestricted:
            [self notifyCameraAuthorizationResticted];
            break;
        case AVAuthorizationStatusAuthorized:
        case AVAuthorizationStatusNotDetermined:
            [self embedBarCodeScannerView];
            [self startCapture];
            break;
    }
}
`

In my case, the issue was happening on an iOS 10 simulator only. The issue was not occurring on an iOS 10 device.

**Comment by rayapudicb** [comment]
hi
- (void)startBarCodeCapture {
if ([[AVCaptureDevice devicesWithMediaType:AVMediaTypeVideo] count] == 0) {
[self notifyCameraNotAvailable];
return;
}
i didnt get ur above point 

my Code is 

-(void)viewDidAppear:(BOOL)animated{
    
 //   [self createCam];
    [self goToCamera];
    [super viewDidAppear:YES];
}

-(void)goToCamera{
    AVAuthorizationStatus authStatus = [AVCaptureDevice authorizationStatusForMediaType:AVMediaTypeVideo];
    switch (authStatus) {
        case AVAuthorizationStatusRestricted:
            [self camDenied];
        case AVAuthorizationStatusNotDetermined:{
            [AVCaptureDevice requestAccessForMediaType:AVMediaTypeVideo completionHandler:^(BOOL granted)
             {
                 if(granted)
                 {
                     NSLog(@"Granted access to %@", AVMediaTypeVideo);
                     [self createCam];
                 }
                 else
                 {
                     NSLog(@"Not granted access to %@", AVMediaTypeVideo);
                     [self camDenied];
                 }
             }];
        }
        case AVAuthorizationStatusAuthorized:
            [self createCam];
            break;
            
        default:
            break;
    }
}

-(void)createCam
{
    
    dupilicateResult=@"";
    [self performSelector:@selector(removeSpinner) withObject:nil afterDelay:0.5f];
    if(appInstance.capture==nil)
        appInstance.capture = [[ZXCapture alloc] init];
    appInstance.capture.camera = appInstance.capture.back;
    appInstance.capture.focusMode = AVCaptureFocusModeContinuousAutoFocus;
    appInstance.capture.rotation = 90.0f;
    appInstance.capture.layer.frame = CGRectMake(0, 150, self.view.frame.size.width, self.view.frame.size.height);
    appInstance.capture.delegate = self;
    [self.view.layer addSublayer:appInstance.capture.layer];
    [appInstance.capture start];
    
}

**Comment by maxkorytko** [comment]
Hey @rayapudicb ,

My code checks if camera is available and if the app has permissions to use it. If both conditions are met, I go ahead and try to initialize and embed the camera capture view. Once again, in my case the issue was happening because I was trying to do the latter when camera was not available, which is the case with the iOS simulator.

**Comment by rayapudicb** [comment]
I fixed it 
http://useyourloaf.com/blog/privacy-settings-in-ios-10/
U need to check add the property in plist and the before accessing the camera u need to write the code snipit 
-(void)goToCamera{
AVAuthorizationStatus authStatus = [AVCaptureDevice authorizationStatusForMediaType:AVMediaTypeVideo];
switch (authStatus) {
case AVAuthorizationStatusRestricted:
[self camDenied];
case AVAuthorizationStatusNotDetermined:{
[AVCaptureDevice requestAccessForMediaType:AVMediaTypeVideo completionHandler:^(BOOL granted)
{
if(granted)
{
NSLog(@"Granted access to %@", AVMediaTypeVideo);
[self createCam];
}
else
{
NSLog(@"Not granted access to %@", AVMediaTypeVideo);
[self camDenied];
}
}];
}
case AVAuthorizationStatusAuthorized:
[self createCam];
break;

    default:
        break;
}

}
